### ISSUE TITLE
We should never use HTML markup in PHP code

### ISSUE THREAD

**Issue by bohart** [boddyua/np#3]
https://github.com/boddyua/np/blob/58bf0dbe38ce1cb9de66f30d5adde3e0add7fbd3/web/modules/custom/exchange_rates/src/Plugin/Block/FrontpageBlock.php#L68

Solution: html_tag element should be used (in case 1 or 2 HTML elemets) OR new twig tepmlate (our case).

**Comment by boddyua** [comment]
now use twig
